// Code generated by protoc-gen-go-hash. DO NOT EDIT.
// versions:
// 	protoc-gen-go-hash v0.1.0
// 	protoc             v3.15.8
// source: no_message.proto

package testdata

import (
	"fmt"

	"github.com/mitchellh/hashstructure/v2"
)
