// Code generated by protoc-gen-go-hash. DO NOT EDIT.
// versions:
// 	protoc-gen-go-hash v0.1.0
// 	protoc             v3.15.8
// source: one_message.proto

package testdata

import (
	"fmt"

	"github.com/mitchellh/hashstructure/v2"
)

func (x *Hello) Hash() (uint64, error) {
	if x == nil {
		return 0, fmt.Errorf("message is defined as nil")
	}

	return hashstructure.Hash(*x, hashstructure.FormatV2, nil)
}
