// Code generated by protoc-gen-go-hash. DO NOT EDIT.
// versions:
// 	protoc-gen-go-hash v0.0.3
// 	protoc             v3.15.8
// source: two_messages.proto

package testdata

import (
	"fmt"

	"github.com/mitchellh/hashstructure/v2"
)

func (x *FirstMessage) Hash() (uint64, error) {
	if x == nil {
		return 0, fmt.Errorf("message is defined as nil")
	}

	return hashstructure.Hash(*x, hashstructure.FormatV2, nil)
}
func (x *SecondMessage) Hash() (uint64, error) {
	if x == nil {
		return 0, fmt.Errorf("message is defined as nil")
	}

	return hashstructure.Hash(*x, hashstructure.FormatV2, nil)
}
